- _includes/selector.html
Just reorders the conda channels for the cuda-python fix.
> Reorder conda channels

- index.md
This PR fixes a broken link identified by external review.
> Fix broken link to Multi-GPU with Dask-cuDF.

- merlin.md
This PR fixes some dead links on the Merlin page.
> Fix Merlin links.

- _data/releases.yml
PR updates RAPIDS versions on main website
> Update site versions

- hpc.md
update correct json filename for hpc deploy doc
> Small Typo Fix in HPC.md

- _includes/selector.html
- start.md
Removed outdated system req blog link on get started, broken cuGraph source link, and clearer req numbers.
> Link fixes

- content/learn-more/_index.html
- layouts/404.html
- layouts/partials/footer.html
- netlify.toml
This PR includes the following changes:
- DRYs up the `netlify.toml` config
- Updates some hardcoded URLs to use relative URLs
The result of the first change above is that now our `_redirects` file should work on pull-request preview environments.
> Update `netlify` config

- content/_index.html
Minor updates for the v23.04 release
Depends on https://github.com/rapidsai/docs/pull/362
> Update for v23.04 release

- content/_index.html
Just updates for the v23.06 release.
See:
- https://github.com/rapidsai/docs/pull/396
- https://github.com/rapidsai/docs/pull/394
> Updates for v23.06 release

- _redirects
- content/smsl.html
add back the smsl redirect.  may need additions
> readd smsl redirects

- content/_index.html
- content/cudf-pandas/_index.html
- Adds a note that cudf.pandas is part of the regular cuDF package (may not be obvious to a totally new reader)
- Slight tweaks to titles/chart captions
> Minor cudf-pandas tweaks to landing page and homepage

- content/_index.html
This PR updates the announcement buttons on the homepage.
> Update announcement button headings.

- content/_index.html
Updates for v23.12 release
Also adds back the announcements for release & Pascal deprecation.
Depends on rapidsai/docs#461
> Updates for v23.12 release

- go.mod
- go.sum
- hugo.yaml
- netlify.toml
- scripts/devcontainer-init.sh
This PR updates the versions of Docsy and Hugo that we use to the current latest.
> Update `docsy` and `hugo`

- layouts/index.html
Standard updates for release & update Pascal=>Volta
> Updates for 24.02 release

- layouts/index.html
- layouts/page/cudf-pandas.html
Removed Beta and new mentions, added updated benchmark.
> updated cudf-pandas content

- layouts/index.html
- layouts/page/cudf-pandas.html
This PR:
- Adds a brief cudf.pandas on Colab update to the homepage "New" section
- Updates cudf.pandas landing page to indicate GA
> cudf.pandas updates (homepage and landing page)

- layouts/index.html
Just updates to the versions. Update URLs were checked.
> Updates for 24.06 release

- layouts/page/ecosystem.html
- scripts/devcontainer-init.sh
Adding per #382 request. Trying PR again without conflicts.
> Added NeMo Curator Section

- layouts/index.html
Bump versions for `24.08` and fix URLs
See also #388
Partially addresses: rapidsai/build-planning#73
> Updates for RAPIDS 24.08

- layouts/partials/hooks/head-end.html
ReFixing #391 per @bdice cleaner  PR request.
> Added prod rapids cookie banner

- layouts/index.html
Switching to miniforge quickstart instructions
> Switching to miniforge quickstart instructions

- content/_partners/google-colab/index.md
- layouts/index.html
- layouts/page/cudf-pandas.html
also removed conda install
closes #405 
Updates:
> update colab links with github

- layouts/index.html
Bumps the versions to 24.10 and Python to 3.12
> Updates for 24.10 release

- layouts/partials/hooks/head-end.html
Fixed branch issue with #395 - sorry!
> updated cookie banner

- layouts/index.html
Companion pull request for https://github.com/rapidsai/docs/pull/559.
> Declare Linux support via glibc versions

- layouts/page/cudf-pandas.html
Addresses cuDF [VDR feedback](https://github.com/rapidsai/cudf/issues/17093)
> add links to more cudf pandas notebooks

- layouts/index.html
Bump the versions to 25.02 and updates cuda version to 12.8
> Updates for 25.02 release

- ci/release/update-version.sh
This should be run during our regular release cycles.
The script would produce diffs similar to https://github.com/rapidsai/rapids.ai/pull/424/files
> Add update-version.sh

- layouts/index.html
> Update for 25.08
