rapidsai/rapids.ai

- _includes/selector.html
- merlin.md
- start.md
We will no longer be uploading development containers to NGC, only Docker Hub. This PR updates the selector logic to disable development containers when selecting NGC as the image location.
> Update selector to disable development containers on NGC.

- _config.yml
- _drafts/templates/new-default-layout.md
- _drafts/templates/new-short-layout.md
- _redirects
- start.md
This PR is a continuation of #275.
Since we've recently switched our site hosting to Netlify, and therefore have access to server side redirects via the `_redirects` file, we can remove the `jekyll-redirect-from` plugin (which does client side redirects) and replace any instances where it was used with proper server side redirects.
This PR makes those changes.
> Update existing redirects

- _redirects
I found a reference in an issue to `/cloud.html`. That page just 404s, and I think it probably always has and the link was a typo. But still thought it might be good to redirect that too just in case `/cloud.html` is used elsewhere.
> Redirect cloud.html to deployment docs

- pip.md
The WSL page we previously linked to has updated its guide to have users install CUDA 12 - I changed the link to be the archive link to CUDA 11.8 so we don't need to worry about this again until we start supporting both -cu11 and -cu12.
> Updating WSL Cuda Install Link

- _data/releases.yml
- _includes/selector.html
- pip.md
- start.md
- wsl2.md
This PR updates our release selector for 23.02. @charlesbluca noticed that our Python versions have been incorrect for nightly versions of 23.02 (Python 3.9 has been dropped but has been showing on the release selector for nightly users).
@sevagh Can you please review the pip changes?
I would appreciate a critical eye from other reviewers as well. 🙏
> Platform support updates for 23.02.

- _includes/selector.html
Resolves https://github.com/rapidsai/docker/issues/533
CUDA 11.8 is only supported on Ubuntu 22.04, so disable various selections to enforce this.
Ref: https://github.com/rapidsai/docker/pull/526
> Only allow CUDA 11.8 for Ubuntu 22.04

- config.toml
- content/_index.html
- content/branding/_index.html
- content/drafts/events.html
- content/drafts/rsn.html
- content/drafts/templates.html
- content/ecosystem/_index.html
- content/featured/_index.html
- content/learn-more/_index.html
- content/news/_index.html
- layouts/_default/baseof.html
- static/css/custom.css
- static/manifest.json
- static/site.webmanifest
This reorders page titles so that they look like `Ecosystem | RAPIDS` instead of `RAPIDS.ai | Ecosystem`. This aligns with best-practices guides I found for SEO and accessibility:
https://www.youtube.com/watch?v=9mVQaePha7M&ab_channel=Nomensa
https://blog.hubspot.com/blog/tabid/6307/bid/5984/spilling-seo-juice-3-dos-and-don-ts-for-writing-great-page-titles.aspx
https://webmasters.stackexchange.com/questions/16251/should-site-title-be-before-or-after-page-title
> Reorder page titles.

- _redirects
In preparation for GTC, add a redirect to the (currently private) tutorial repo.
cc: @JohnZed
> Add redirect to RAPIDS tutorial GitHub repo

- content/_index.html
The "quick install" command doesn't work when copied because it contains an escaping backslash `\` that isn't followed by a newline character. We can either insert a newline OR remove the backslash. I prefer to remove the backslash and treat it as a one-liner.
> Fix quick installation command.

- content/_index.html
Looks like this home page layout is larger than it should be.
Changing the CSS class from `is-half` to `is-one-third` like the other sections seems to resolve it.
> Fix home page layout

- content/_index.html
There’s a UI issue on mobile with the announcements. The AI and Data Science Virtual Summit overruns the page on mobile, causing scrolling to behave poorly. We probably need a proper CSS fix for this to allow line wrapping but for now I’m just going to insert a linebreak.
> Add line break to make text more mobile friendly.

- layouts/index.html
Same reasons as in https://github.com/rapidsai/docs/pull/479
> Drop leading zero in pip install

- layouts/index.html
Updating versions for the `24.04` release.
Looks like https://github.com/rapidsai/cugraph/pull/4169 renamed the `cugraph` notebook, so its URL is updated.
> Updates for 24.04 release

- layouts/index.html
Following the removal of Cent OS 7 support across RAPIDS, this PR removes any Cent OS 7 references from the home page
> Remove centos refs from homepage

- layouts/index.html
Reverts rapidsai/rapids.ai#377.
Following a conversation with @bdice, these changes should be merged with the `24.06` release.
> Revert "Remove centos refs from homepage"

- layouts/page/polars-gpu-engine.html
Did the following edits-
1. Dataset sizes in the x-axis for the 'time vs dataset size' benchmark graph were [20GB,40GB,60GB]. However, the perflab experiments were done on [20GB, 40GB, 80GB]. See data [HERE](https://nvidia-my.sharepoint.com/:x:/r/personal/manass_nvidia_com/Documents/TPCH-Polars%20Update.xlsx?d=wf3ff2e0bc5fc44dc86b08a4bfed7e79b&csf=1&web=1&e=aGKSC5) (Tab: Aggregate (Datasets)). Changed 60GB to 80GB
2. Changed the location of [Open Beta] to align with the originally decided content page layout- https://docs.google.com/document/d/1h2Ynp0sniNuQ1k7Cfx64DYauaLJnadIkVpWCrXudaK0/edit
> Minor edits to polars gpu engine page on rapids.ai

- layouts/404.html
This PR adjusts the 404 page link to be relative instead of absolute.
> Make 404 Link relative

- content/_partners/_index.md
- content/drafts/_index.md
- content/drafts/events.md
- content/drafts/rsn.md
- content/drafts/templates.md
- hugo.yaml
- netlify.toml
- vercel.sh
The `_partners` bundle is intended to be headless, but it currently shows up on our sitemap.
This PR includes some changes to ensure that the `_partners` bundle is actually headless.
It updates some frontmatter and the Hugo version. The older Hugo version was not respecting the headless frontmatter.
It also sets `enableGitInfo: true` in the `hugo.yaml` config, since this seems to be required to get Vercel to show the `lastmod` date in the sitemaps.
Note, this doesn't update Hugo to the latest version since that also requires updating our theme, Docsy, which is a bit more involved. That'll come later.
> Fix headless `_partners` bundle

- _redirects
Adds temporary redirect for nx-cugraph, to be removed when nx-cugraph landing page is in place.
More background info here (filed to wrong repo): https://github.com/rapidsai/docs/issues/545
> Adds temporary redirect for nx-cugraph, to be removed when nx-cugraph landing page is in place.

- layouts/index.html
This updates the cuGraph benchmarks to show results for latest NetworkX zero code change results, as well as the messaging around "zero code change", which is consistent with cuDF's "no code change" Pandas messaging (this also changes cuDF's "no code change" to "zero code change" for consistency).
> Updates cuGraph benchmarks to reflect latest NetworkX zero code change results

- layouts/index.html
Update “Test Drive cuDF” on homepage to new notebook link
> Replace cuDF notebook with non-Drive link

- layouts/page/cudf-pandas.html
This PR updates the Colab notebook URLs on the cudf-pandas page to correctly redirect to the cuDF pandas notebooks rather than Polars.
> Fix Colab notebook URLs on cudf-pandas overview page

- layouts/page/ecosystem.html
I noticed that all the libraries on the Ecosystem page mention their PyData (CPU) counterparts, except for cuCIM. This adds crucial information that improves user discovery.
> Update cuCIM description to mention similar Python APIs.

- layouts/index.html
Update the docs to use non-zero-padded (PEP440) version format. See https://github.com/rapidsai/rapids.ai/pull/432#discussion_r1956766200
> Fix zero-padded wheel versions

- layouts/page/cudf-pandas.html
This improves the documentation by clarifying that `cudf.pandas` must be enabled *before importing or using pandas* in order to provide GPU acceleration.
I also touched up a few formatting bits to improve the page.
> Clarify that cudf.pandas should be enabled before importing pandas.

- hugo.yaml
- layouts/partials/hooks/head-end.html
This fixes the Open Graph image tag of our site's metadata to improve social media previews.
> Fix Open Graph image tag for better social media previews

- layouts/page/cuml-accel.html
Enhances the cuML Accelerate page with improved code examples and better user experience.
- **Fixed the broken "Get Started" anchor link**
- **Added installation instructions** for `cuml.accel` via `cuml`
- **Updated code example:** replaced KMeans with a complete RandomForest workflow
- **Added profiling section:** included `%%cuml.accel.profile` magic command example
Fixes https://github.com/rapidsai/rapids.ai/issues/453
> Improve the cuml.accel landing page
